name: Build C++ FocusPro Final
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore NuGet Packages
        run: nuget install sfml_graphics -Version 2.6.0 -OutputDirectory packages

      - name: Build with MSBuild
        run: msbuild FocusPro.vcxproj /p:Configuration=Release /p:Platform=x64 /p:AdditionalIncludeDirectories="packages/sfml_graphics.2.6.0/build/native/include" /p:AdditionalLibraryDirectories="packages/sfml_graphics.2.6.0/build/native/lib/x64"

      - name: Copy DLLs and Sound
        run: |
          copy packages\sfml_graphics.2.6.0\build\native\bin\x64\*.dll x64\Release\
          if (Test-Path "start.wav") { copy start.wav x64\Release\ }

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FocusPro-Direct-Build
          path: x64/Release/