name: Build C++ FocusPro
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore SFML
        # SFML download කරලා 'deps' කියන folder එකට දානවා පටලවන්නේ නැතුව
        run: nuget install sfml_graphics -Version 2.6.0 -OutputDirectory deps

      - name: Build with MSBuild
        # Compile කරද්දී headers තියෙන තැන බලෙන්ම පෙන්වනවා
        run: |
          $includePath = "${{ github.workspace }}\deps\sfml_graphics.2.6.0\build\native\include"
          $libPath = "${{ github.workspace }}\deps\sfml_graphics.2.6.0\build\native\lib\x64"
          msbuild FocusPro.vcxproj /p:Configuration=Release /p:Platform=x64 /p:AdditionalIncludeDirectories="$includePath" /p:AdditionalLibraryDirectories="$libPath"

      - name: Copy DLLs
        run: |
          copy deps\sfml_graphics.2.6.0\build\native\bin\x64\*.dll x64\Release\

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FocusPro-v3-Final
          path: x64/Release/